### ISSUE TITLE
Bug - Samsung back button doesn't work as intended on every screen

### ISSUE THREAD

**Issue by carrot987** [tamighi/todocal#18]
How it behaves currently : 
![:(](https://github.com/tamighi/todocal/assets/155832057/60a19ff6-33a0-40e5-9414-694f251ecf37)

The goal behavior: 
![:D](https://github.com/tamighi/todocal/assets/155832057/2ac5f4e9-8f94-46ca-9b53-93f2eb873410)

**Comment by tamighi** [comment]
#31
