### ISSUE TITLE
Task repetition option

### ISSUE THREAD

**Issue by carrot987** [tamighi/todocal#7]
I would like to propose the addition of a new feature that allows users to set repetitive tasks with customizable recurrence intervals. 

Currently, when creating a new task, it is unitary. My proposition is that users should be able to specify whether the task should repeat every week, every day, or at a custom interval of their choice. 

Additionally, users should have the option to define the duration or the end date for the repetition, or undetermined period of time (infinite). In the case of infinity, when deleting one of the task of a serie, the program should inquire whether the user wants to delete all the tasks of the serie, only the selected one, or all the tasks from this date.

**Comment by tamighi** [comment]
Do you have an idea on how we could implement this ?

**Comment by carrot987** [comment]
I'll get back to you when I've got more info.
In the meanwhile, we've discussed it a little together which gave birth to some clues.
